import type { Metadata } from "next";
import { Roboto } from 'next/font/google'

import "./globals.css";

const roboto = Roboto({
  weight: "700",
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Image Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preload" href="https://picsum.photos/id/20/1000/600" as="image" type="image/jpg" />
        <link rel="preload" href="https://picsum.photos/id/20/1200/600" as="image" type="image/jpg" />
        <link rel="preload" href="https://picsum.photos/id/20/1600/600" as="image" type="image/jpg" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet"/>
      </head>
      <body className={roboto.className}>
        {children}
      </body>
    </html>
  );
}
